services:

  # Projects database events to the 'projections' service.
  ambar-emulator:
    image: ambarltd/emulator:v1.8
    command: "run --data-path /app/data --config /app/emulator-config.yaml"
    volumes:
      - ./emulator-config.yaml:/app/emulator-config.yaml
      - ./events.database:/app/events.database

  # Write events into the database.
  service-writer:
    image: node:23
    init: true
    command: node /app/service-writer.js --database /app/events.database
    volumes:
      - ./service-writer.js:/app/service-writer.js
      - ./events.database:/app/events.database

  # Build read models from events.
  service-projections:
    image: node:23
    init: true
    command: node /app/service-projections.js
    volumes:
      - ./service-projections.js:/app/service-projections.js
    ports:
      - 8080:8080
