services:

  # Projects database events to the 'projections' service.
  ambar-emulator:
    image: ambarltd/emulator:v1.8
    command: "run --data-path /app/data --config /app/config.yaml"
    volumes:
      - ./volumes/emulator-config.yaml:/app/config.yaml
      - ./volumes/file.database:/app/file.database

  # Write events into the database.
  writer:
    image: node:23
    init: true
    command: node /app/writer.js --database /app/file.database
    volumes:
      - ./writer.js:/app/writer.js
      - ./volumes/file.database:/app/file.database

  # Build read models from events.
  projections:
    image: node:23
    init: true
    command: node /app/projections.js
    volumes:
      - ./projections.js:/app/projections.js
    ports:
      - 8080:8080
