services:

  # Projects database events to the 'projections' service.
  ambar-emulator:
    image: ambarltd/emulator:v1.8
    command: "run --data-path /opt/emulator/data --config /opt/emulator/config.yaml"
    volumes:
      - ./volumes/emulator-config.yaml:/opt/emulator/config.yaml
      - ./volumes/emulator-data:/opt/emulator/data
      - ./volumes/file.database:/opt/emulator/file.database

  # Write events into the database.
  writer:
    image: node:23
    command: node /app/writer.js
    volumes:
      - ./writer.js:/app/writer.js

  # Build read models from events.
  projections:
    image: node:23
    command: node /app/projections.js
    init: true
    volumes:
      - ./projections.js:/app/projections.js
    ports:
      - 8080:8080
